CreateFile = function(filePathValue) {
  if(file.exists(filePathValue) == FALSE) {
    file.create(filePathValue)
    return("File Created")
  }
  else {
    return("File Already Exists")
  }
}
CreateFile("E:\\Venkatesan\\RProgramming\\POC\\AutoGeneratedFiles\\testCreate.csv")